### ISSUE TITLE
Need instructions to self learning students

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/sql-novice-survey#110]
We should have instructions for how learners can (1) get the data that we are using and (2) how to start the SQLite.

**Comment by kdmaas** [comment]
As a self-paced learner I can only second that!

**Comment by timtomch** [comment]
This information is currently in the "discussion" section [1], as mentioned on the index page. But I agree that it is a bit hidden. I suggest adding a short version of the discussion/setup text and put it in a "getting started" box on the index page, much as the Python lesson.

[1] https://swcarpentry.github.io/sql-novice-survey/discussion.html

**Comment by timtomch** [comment]
I've made an attempt at summarizing the setup instructions on the index page. I haven't done a pull request yet because I'd like some feedback first: http://labs.timtom.ch/sql-novice-survey/
@kdmaas: would this kind of stuff have helped?
@acabunoc: what do you think?

Source: https://github.com/timtomch/sql-novice-survey

Thanks

**Comment by timtomch** [comment]
Woops, @rgaiacs already addressed this in https://github.com/swcarpentry/sql-novice-survey/pull/112 - sorry.

**Comment by gvwilson** [comment]
@rgaiacs now fixed?
