### ISSUE TITLE
no sqlite prompt

### ISSUE THREAD

**Issue by aurielfournier** [swcarpentry/sql-novice-survey#124]
I'm trying to work through the sql lesson. 

Windows 10, working through git bash. 

I run 

sqlite3 survey.db

and I do not get the prompt that is outlined in the instructor.md lesson. I just got a cursor. 

At first I assumed something was wrong, but no, it works just fine from that cursor, there is just never a prompt

sqlite3 --version 

3.8.4.3 2014-04-03 16:53:12 a611fa96c4a848614efe899130359c9f6fb889c3

**Comment by gvwilson** [comment]
Can someone else with a Windows 10 machine please check this?

**Comment by kyrretl** [comment]
I did a clean install (had no previous versions of git or swc installations) of Git for windows on Windows 10 Pro (version 1511 - OS Build 10586.545) and installed the newest version of the software carpentry windows installer and did *not* experience the same issue.

I installed Git first by following the steps outlined in the swc Bash shell guide
https://swcarpentry.github.io/workshop-template/

Then the software carpentry windows installer:
https://github.com/swcarpentry/windows-installer/releases/tag/v0.3

Git version 2.9.3.windows.2 64-bit (MINGW64) date: 25th august 2016
Sqlite from the software carpentry windows installer - version: 3.9.2 2015-11-02 18:31:45 bda77dda9697c463c3d0704014d51627fceee328

Which version of Git did you install? Did you use the newest git for windows? 

Here, https://github.com/swcarpentry/windows-installer/issues/53,
it is stated that the link to the git that was used (msysgit) pointed to a deprecated version.
Today the link to git is now updated to https://git-for-windows.github.io/ which was the one I used,
but this might not have been the case in January when you encountered your problem.

There might also be an issue with discrepancy between 64bit and 32bit Git -  however I tried to use both and failed to reproduce your issue.

That said, I did manage to reproduce the issue by using the 2.9.3.windows.2 version of Git (both 32 and 64bits), *by not* choosing to check "Use Windows' default console window", but rather keep "Use MinTTY (the default terminal of MSYS2) as stated in the SWC Bash shell setup guide.

I find it a bit confusing that the guide says *keep*, when default is "Use MinTTY". It might cause the users to quickly click next because they believe that you can just keep all the default settings.

Have you tried to uninstall and reinstall both git and the swc installer to see if the problem still persists?

**Comment by debpaul** [comment]
@aurielfournier me too. you wrote 
> I'm trying to work through the sql lesson. Windows 10, working through git bash. I run
`sqlite3 survey.db`

I can only get this to work, IF if i do the git clone step `git clone http://github.com/swcarpentry/sql-novice-survey.git` from the Instructor notes.

IF I follow the student software installation instructions, typing `sqlite3` at the bash prompt doesn't work, doesn't start sqlite3.

**Comment by debpaul** [comment]
@kyrretl @gvwilson I did not try to uninstall / reinstall. I did go through the same steps on another Win 10 platform. Same issue as above.

**Comment by hoytpr** [comment]
Just wanted to note this is still an issue on Windows10. BUT sqlite3 is actually working, but without a prompt. Also trying to add a prompt does not work (e.g. .prompt sqlite3>).

**Comment by sdtaylor** [comment]
We ran into this at a workshop. There would be no prompt inside sqlite, and it would pretty much stop working if you mistyped any command. We found it only happened in git bash, and a work around was to run sqlite3 thru the old windows command prompt.

**Comment by henrykironde** [comment]
We have new releases of SQlite which I do think has solved some of the bugs. We also have added the more instructions. We shall open in case we get a new report on this.
