### ISSUE TITLE
Meaning of `Survey.quant` values

### ISSUE THREAD

**Issue by cwant** [swcarpentry/sql-novice-survey#239]
The `Survey` table has a field called `quant` that holds what type of reading was taken. The values in this column are `rad`, `sal`, and `temp`. There is no legend that explains what these mean on the page where the data is introduced (the selecting data chapter). Much later in the course it's mentioned that these mean 'radiation', 'salinity' and 'temperature', but I think it would also be helpful to mention the meaning earlier when the data is presented.

**Comment by nathan-hook** [comment]
I also got caught up on what quant was and after a quick google search it is short for Quantitative, which has a meaning of "relating to, measuring, or measured by the quantity of something rather than its quality."

Which I don't feel totally fits what the column is actually trying to describe, perhaps a better word would be measurement or category?  Just a thought.

But, it could also be a representation of the original data and wanting to stay 'true' to the way that the records were originally recorded.

**Comment by remram44** [comment]
I assumed it was short for "quantity"
