### ISSUE TITLE
explanation of UNION vs UNION ALL

### ISSUE THREAD

**Issue by raybellwaves** [swcarpentry/sql-novice-survey#256]
Given that ALL hasn't been introduced so far and the example works the same without it do you think it is worth dropping it?

Changing
```
SELECT AVG(a) FROM (
    SELECT 1 AS a
    UNION ALL SELECT NULL
    UNION ALL SELECT 5);
```
to
```
SELECT AVG(a) FROM (
    SELECT 1 AS a
    UNION SELECT NULL
    UNION SELECT 5);
```

**Comment by henrykironde** [comment]
@raybellwaves for the issue. We shall discus this and find a way of better representing the solution.
Personally, I think there should be an explanation of UNION and UNION ALL in that solution.

**Comment by remram44** [comment]
`UNION ALL` is the simpler construct IMHO. It does less than `UNION` and is therefore faster. I believe it is more widely used than `UNION`. People are likely to encounter it "in the wild" and therefore I don't think it's right to just remove it.


The fact that the keyword is two words instead of one doesn't mean anything (`ALL` is not a keyword and does nothing by itself).

But I agree that episode `04-calc` should be updated to introduce both.

**Comment by raybellwaves** [comment]
Thanks for the discussion on this. This is my first exposure to SQL to so I didn't know `UNION ALL` was the construct. A quick google pointed me to https://www.w3schools.com/sql/sql_any_all.asp and I thought similar to [python numpy all](https://docs.scipy.org/doc/numpy/reference/generated/numpy.all.html) would return some kind of boolean.

Discussion about `UNION` and `UNION ALL` beforehand would be useful.

**Comment by henrykironde** [comment]
Thanks for the contribution, I will close this issue since we have discussed this and added #257
