### ISSUE TITLE
Errata in Filtering Lesson of Using Databases and SQL

### ISSUE THREAD

**Issue by bmagill1250** [swcarpentry/sql-novice-survey#74]
In the Filtering lesson of Using Databases and SQL I came across the following in the following:
 
<<<<<<< HEAD (The parentheses around the individual tests aren't strictly required, but they help make the query easier to read.)
Date types
======= >>>>>> 06563c2f46681b04db26066a231d9dc237c0ffa0
 
It occurs right after the SQL statement:
 
SELECT * FROM Visited WHERE site="DR-1" AND dated<="1930-00-00";
 
Looking at the files in the repository, I did not see it in 03-filter.md, but it is in the page 03-filter.html.

**Comment by wking** [comment]
On Sun, Apr 19, 2015 at 06:47:20PM -0700, bmagill1250 wrote:
> Looking at the files in the repository, I did not see it in
> 03-filter.md, but it is in the page 03-filter.html.

This was just a missed merge conflict that wasn't resolved before
c0756e2 (fixing merge conflict, 2015-03-26) was committed.  The
Markdown source was fixed in a9df6c10 (03-filter.md: Remove
conflict-markers around the date type callout, 2015-03-28, #53) and
also in the parallel 8355713f (Remove git conflict markup and text,
2015-04-02, #59).  The entry in the HTML should go away once the
maintainers rebuilt the repositories HTML to pick up those changes to
the Markdown source.

**Comment by acabunoc** [comment]
Sorry this took so long -- should be fixed now!
